### ISSUE TITLE
V3 PCB?

### ISSUE THREAD

**Issue by Friendly0Fire** [adafruit/Adafruit-Bluefruit-LE-USB-Friend-and-Sniffer-PCB#2]
I tried looking around, but I couldn't find a board layout for the V3 board (without the SWD connector). I'm looking to make a dimensionally accurate 3D printed case for it and it'd be a lot easier to do this with an up to date PCB layout I could use for CAD.

**Comment by kattni** [comment]
@Friendly0Fire I have added the latest board files.
