### ISSUE TITLE
Setting up in Kali Linux is the Blue Fruit Defective 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [adafruit/Adafruit-Bluefruit-LE-USB-Friend-and-Sniffer-PCB#3]
Is the Blue Fruit Sniffer plug in play on Kali Linux I plugged it in but nothing is happening can you guide me on installation I would highly appreciate it as I'm new to Bluetooth traffic captures. I'm kind of stuck.

**Comment by ladyada** [comment]
tutorial is here
https://learn.adafruit.com/introducing-the-adafruit-bluefruit-le-sniffer
we have not tried Kali

**Comment by ChillVibesMushroom** [comment]
> tutorial is here https://learn.adafruit.com/introducing-the-adafruit-bluefruit-le-sniffer we have not tried Kali

I have it up and running right I'm pulling packets from BLE devices that aren't in the same room as me but are around I was wondering 

Would you happen to have any resource links that can guide on on some basic cool things to do with the sniffer
