### ISSUE TITLE
How can I get a better scan

### ISSUE THREAD

**Issue by ChillVibesMushroom** [adafruit/Adafruit-Bluefruit-LE-USB-Friend-and-Sniffer-PCB#4]
I've managed to get the sniffer capturing all devices but I noticed sometimes it will capture malformed packets and I was wondering how I can get a better scan from the sniffer. All the steps provided I have followed on installation or is that normal to get malformed packets currently I am at work and I'll have to get back to you in 10 hours have a great day okay.

**Comment by ChillVibesMushroom** [comment]
This is what we are looking at here. The BLE Friend is picking up malformed packets. 



![IMG_20220509_205559218](https://user-images.githubusercontent.com/99580833/167527200-802c209d-fed6-44c9-962b-bc51e2e99d24.jpg)

**Comment by ladyada** [comment]
we just run the firmware from nordic, we dont have any other insight into how the firmware works, you could try asking nordic for advice on sniffing BLE they have a helpful forum
